# Generated by Django 4.2 on 2023-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meditation_length', models.IntegerField(default=15, max_length=3)),
                ('interval_length', models.IntegerField(default=5, max_length=3)),
            ],
        ),
    ]
